import { test, expect } from '@playwright/test';
test('Studio: metadata-only listing, exact cell editing, drawer metadata, audit, and responsive layout', async ({ page }) => {
  const browserErrors: string[] = []; page.on('pageerror', e => browserErrors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Projects', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Core API', exact: true }).click();
  await expect(page.locator('[data-secret-row]')).toHaveCount(8);
  expect(await page.locator('body').textContent()).not.toContain('synthetic-jwt-secret');
  const row = page.locator('[data-secret-row]').filter({ has: page.locator('.secret-name code', { hasText: /^DATABASE_URL$/ }) });
  expect(await row.locator('.value-col button').count()).toBe(3); // value trigger, reveal, copy; no pencil
  const beforeHeight = (await row.boundingBox())!.height;
  await row.getByRole('button', { name: 'Edit value for DATABASE_URL', exact: true }).click();
  const input = row.getByRole('textbox', { name: 'Value for DATABASE_URL' });
  await expect(input).toBeVisible();
  await expect(row.locator('.value-col button')).toHaveCount(2);
  await expect(row.getByRole('button', { name: 'Reveal DATABASE_URL', exact: true })).toHaveCount(0);
  expect((await row.boundingBox())!.height).toBe(beforeHeight);
  await input.fill('synthetic-cancelled-value'); await input.press('Escape');
  await row.getByRole('button', { name: 'Edit value for DATABASE_URL', exact: true }).click();
  await expect(input).not.toHaveValue('synthetic-cancelled-value');
  const replacement = 'synthetic-browser-commit-' + Date.now();
  await input.fill(replacement); await input.press('Enter');
  await expect(page.getByRole('status')).toContainText('new version');
  await row.getByRole('button', { name: 'Reveal DATABASE_URL', exact: true }).click();
  await expect(row.locator('.value-trigger')).toHaveText(replacement);
  await row.getByRole('button', { name: 'Hide DATABASE_URL', exact: true }).click();
  await row.getByRole('button', { name: 'Details for DATABASE_URL', exact: true }).click();
  const drawer = page.getByRole('dialog'); await expect(drawer).toBeVisible();
  await expect(drawer).not.toContainText(replacement);
  await drawer.getByRole('button', { name: 'Edit details', exact: true }).click();
  await drawer.getByLabel('Tag', { exact: true }).fill('Database');
  await drawer.getByLabel('Description', { exact: true }).fill('Updated through the metadata drawer');
  await drawer.getByRole('button', { name: 'Save details', exact: true }).click();
  await expect(drawer).toContainText('Updated through the metadata drawer');
  await drawer.getByRole('button', { name: 'Version history', exact: true }).click();
  await expect(drawer).toContainText('Version 2'); await expect(drawer).toContainText('Version 1');
  await drawer.getByRole('button', { name: 'Close dialog' }).click();
  await page.screenshot({ path: 'test-results/studio-secrets.png', fullPage: true });
  await row.getByRole('button', { name: 'Edit value for DATABASE_URL', exact: true }).click();
  await page.screenshot({ path: 'test-results/studio-cell-edit.png', fullPage: true });
  await input.press('Escape');
  await page.getByRole('button', { name: 'Audit log', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Audit log', exact: true })).toBeVisible();
  await expect(page.locator('.audit-table')).toContainText('secret.metadata');
  await expect(page.locator('.audit-table')).toContainText('secret.write');
  expect(await page.locator('.audit-table').textContent()).not.toContain(replacement);
  await page.getByRole('button', { name: 'Core API', exact: true }).click();
  await page.getByRole('button', { name: 'Production', exact: true }).click();
  const productionRow = page.locator('[data-secret-row]').filter({ has: page.locator('.secret-name code', { hasText: /^DATABASE_URL$/ }) });
  await productionRow.getByRole('button', { name: 'Edit value for DATABASE_URL', exact: true }).click();
  await productionRow.getByRole('textbox').fill('synthetic-protected-change'); await productionRow.getByRole('textbox').press('Enter');
  await expect(page.getByRole('dialog')).toContainText('Confirm protected change');
  await page.getByRole('button', { name: 'Back to editing' }).click(); await productionRow.getByRole('textbox').press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Toggle navigation' }).click(); await expect(page.locator('.sidebar')).toBeVisible();
  expect(browserErrors).toEqual([]);
});
test('HTTP API refuses cross-origin requests and lists no plaintext', async ({ request }) => {
  const denied = await request.post('/api/v1/operations', { headers: { Origin: 'https://attacker.invalid', 'X-Coffre-Request': '1' }, data: { requestId: crypto.randomUUID(), command: { type: 'workspace.get' } } });
  expect(denied.status()).toBe(403);
  const invalid = await request.post('/api/v1/operations', { headers: { 'X-Coffre-Request': '1' }, data: { requestId: crypto.randomUUID(), command: { type: 'unrestricted.sql', sql: 'select *' } } });
  expect(invalid.status()).toBe(400);
});
