/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoffreRouteImport } from './routes/_coffre'
import { Route as SoloRouteImport } from './routes/_solo'
import { Route as LivezRouteImport } from './routes/livez'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known.$'
import { Route as CoffreIndexRouteImport } from './routes/_coffre/index'
import { Route as CoffreAccessRouteImport } from './routes/_coffre/access'
import { Route as CoffreAccountRouteImport } from './routes/_coffre/account'
import { Route as CoffreAuditRouteImport } from './routes/_coffre/audit'
import { Route as CoffreSettingsRouteImport } from './routes/_coffre/settings'
import { Route as SoloLoginRouteImport } from './routes/_solo/login'
import { Route as SoloUnregisteredRouteImport } from './routes/_solo/unregistered'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as CoffreProjectsIndexRouteImport } from './routes/_coffre/projects.index'
import { Route as CoffreTokensIndexRouteImport } from './routes/_coffre/tokens.index'
import { Route as CoffreTokensTokenRouteImport } from './routes/_coffre/tokens.$token'
import { Route as CoffreUsersIndexRouteImport } from './routes/_coffre/users.index'
import { Route as CoffreUsersUserRouteImport } from './routes/_coffre/users.$user'
import { Route as SoloApprovalsApprovalRouteImport } from './routes/_solo/approvals.$approval'
import { Route as SoloAuthDeviceRouteImport } from './routes/_solo/auth.device'
import { Route as SoloOauthAuthorizeRouteImport } from './routes/_solo/oauth.authorize'
import { Route as CoffreProjectsProjectIndexRouteImport } from './routes/_coffre/projects.$project.index'
import { Route as CoffreProjectsProjectEnvironmentRouteImport } from './routes/_coffre/projects.$project.$environment'

const CoffreRoute = CoffreRouteImport.update({
  id: '/_coffre',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/_solo',
  getParentRoute: () => rootRouteImport,
} as any)
const LivezRoute = LivezRouteImport.update({
  id: '/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffreIndexRoute = CoffreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAccessRoute = CoffreAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAccountRoute = CoffreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAuditRoute = CoffreAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreSettingsRoute = CoffreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoffreRoute,
} as any)
const SoloLoginRoute = SoloLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SoloRoute,
} as any)
const SoloUnregisteredRoute = SoloUnregisteredRouteImport.update({
  id: '/unregistered',
  path: '/unregistered',
  getParentRoute: () => SoloRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffreProjectsIndexRoute = CoffreProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreTokensIndexRoute = CoffreTokensIndexRouteImport.update({
  id: '/tokens/',
  path: '/tokens/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreTokensTokenRoute = CoffreTokensTokenRouteImport.update({
  id: '/tokens/$token',
  path: '/tokens/$token',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreUsersIndexRoute = CoffreUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreUsersUserRoute = CoffreUsersUserRouteImport.update({
  id: '/users/$user',
  path: '/users/$user',
  getParentRoute: () => CoffreRoute,
} as any)
const SoloApprovalsApprovalRoute = SoloApprovalsApprovalRouteImport.update({
  id: '/approvals/$approval',
  path: '/approvals/$approval',
  getParentRoute: () => SoloRoute,
} as any)
const SoloAuthDeviceRoute = SoloAuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => SoloRoute,
} as any)
const SoloOauthAuthorizeRoute = SoloOauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => SoloRoute,
} as any)
const CoffreProjectsProjectIndexRoute =
  CoffreProjectsProjectIndexRouteImport.update({
    id: '/projects/$project/',
    path: '/projects/$project/',
    getParentRoute: () => CoffreRoute,
  } as any)
const CoffreProjectsProjectEnvironmentRoute =
  CoffreProjectsProjectEnvironmentRouteImport.update({
    id: '/projects/$project/$environment',
    path: '/projects/$project/$environment',
    getParentRoute: () => CoffreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CoffreIndexRoute
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/access': typeof CoffreAccessRoute
  '/account': typeof CoffreAccountRoute
  '/audit': typeof CoffreAuditRoute
  '/settings': typeof CoffreSettingsRoute
  '/login': typeof SoloLoginRoute
  '/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/tokens/$token': typeof CoffreTokensTokenRoute
  '/users/$user': typeof CoffreUsersUserRoute
  '/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/auth/device': typeof SoloAuthDeviceRoute
  '/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/projects/': typeof CoffreProjectsIndexRoute
  '/tokens/': typeof CoffreTokensIndexRoute
  '/users/': typeof CoffreUsersIndexRoute
  '/projects/$project/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/projects/$project/': typeof CoffreProjectsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CoffreIndexRoute
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/access': typeof CoffreAccessRoute
  '/account': typeof CoffreAccountRoute
  '/audit': typeof CoffreAuditRoute
  '/settings': typeof CoffreSettingsRoute
  '/login': typeof SoloLoginRoute
  '/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/tokens/$token': typeof CoffreTokensTokenRoute
  '/users/$user': typeof CoffreUsersUserRoute
  '/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/auth/device': typeof SoloAuthDeviceRoute
  '/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/projects': typeof CoffreProjectsIndexRoute
  '/tokens': typeof CoffreTokensIndexRoute
  '/users': typeof CoffreUsersIndexRoute
  '/projects/$project/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/projects/$project': typeof CoffreProjectsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_coffre': typeof CoffreRouteWithChildren
  '/_solo': typeof SoloRouteWithChildren
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_coffre/access': typeof CoffreAccessRoute
  '/_coffre/account': typeof CoffreAccountRoute
  '/_coffre/audit': typeof CoffreAuditRoute
  '/_coffre/settings': typeof CoffreSettingsRoute
  '/_solo/login': typeof SoloLoginRoute
  '/_solo/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/_coffre/': typeof CoffreIndexRoute
  '/_coffre/tokens/$token': typeof CoffreTokensTokenRoute
  '/_coffre/users/$user': typeof CoffreUsersUserRoute
  '/_solo/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/_solo/auth/device': typeof SoloAuthDeviceRoute
  '/_solo/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/_coffre/projects/': typeof CoffreProjectsIndexRoute
  '/_coffre/tokens/': typeof CoffreTokensIndexRoute
  '/_coffre/users/': typeof CoffreUsersIndexRoute
  '/_coffre/projects/$project/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/_coffre/projects/$project/': typeof CoffreProjectsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/settings'
    | '/login'
    | '/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/tokens/$token'
    | '/users/$user'
    | '/approvals/$approval'
    | '/auth/device'
    | '/oauth/authorize'
    | '/projects/'
    | '/tokens/'
    | '/users/'
    | '/projects/$project/$environment'
    | '/projects/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/settings'
    | '/login'
    | '/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/tokens/$token'
    | '/users/$user'
    | '/approvals/$approval'
    | '/auth/device'
    | '/oauth/authorize'
    | '/projects'
    | '/tokens'
    | '/users'
    | '/projects/$project/$environment'
    | '/projects/$project'
  id:
    | '__root__'
    | '/_coffre'
    | '/_solo'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/_coffre/access'
    | '/_coffre/account'
    | '/_coffre/audit'
    | '/_coffre/settings'
    | '/_solo/login'
    | '/_solo/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/_coffre/'
    | '/_coffre/tokens/$token'
    | '/_coffre/users/$user'
    | '/_solo/approvals/$approval'
    | '/_solo/auth/device'
    | '/_solo/oauth/authorize'
    | '/_coffre/projects/'
    | '/_coffre/tokens/'
    | '/_coffre/users/'
    | '/_coffre/projects/$project/$environment'
    | '/_coffre/projects/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoffreRoute: typeof CoffreRouteWithChildren
  SoloRoute: typeof SoloRouteWithChildren
  LivezRoute: typeof LivezRoute
  McpRoute: typeof McpRoute
  ReadyzRoute: typeof ReadyzRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSplatRoute: typeof AuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_coffre': {
      id: '/_coffre'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoffreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_solo': {
      id: '/_solo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livez': {
      id: '/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof LivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coffre/': {
      id: '/_coffre/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CoffreIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/access': {
      id: '/_coffre/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof CoffreAccessRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/account': {
      id: '/_coffre/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof CoffreAccountRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/audit': {
      id: '/_coffre/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof CoffreAuditRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/settings': {
      id: '/_coffre/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoffreSettingsRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_solo/login': {
      id: '/_solo/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SoloLoginRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/unregistered': {
      id: '/_solo/unregistered'
      path: '/unregistered'
      fullPath: '/unregistered'
      preLoaderRoute: typeof SoloUnregisteredRouteImport
      parentRoute: typeof SoloRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coffre/projects/': {
      id: '/_coffre/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof CoffreProjectsIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/tokens/': {
      id: '/_coffre/tokens/'
      path: '/tokens'
      fullPath: '/tokens/'
      preLoaderRoute: typeof CoffreTokensIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/tokens/$token': {
      id: '/_coffre/tokens/$token'
      path: '/tokens/$token'
      fullPath: '/tokens/$token'
      preLoaderRoute: typeof CoffreTokensTokenRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/users/': {
      id: '/_coffre/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof CoffreUsersIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/users/$user': {
      id: '/_coffre/users/$user'
      path: '/users/$user'
      fullPath: '/users/$user'
      preLoaderRoute: typeof CoffreUsersUserRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_solo/approvals/$approval': {
      id: '/_solo/approvals/$approval'
      path: '/approvals/$approval'
      fullPath: '/approvals/$approval'
      preLoaderRoute: typeof SoloApprovalsApprovalRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/auth/device': {
      id: '/_solo/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof SoloAuthDeviceRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/oauth/authorize': {
      id: '/_solo/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof SoloOauthAuthorizeRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_coffre/projects/$project/': {
      id: '/_coffre/projects/$project/'
      path: '/projects/$project'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof CoffreProjectsProjectIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/projects/$project/$environment': {
      id: '/_coffre/projects/$project/$environment'
      path: '/projects/$project/$environment'
      fullPath: '/projects/$project/$environment'
      preLoaderRoute: typeof CoffreProjectsProjectEnvironmentRouteImport
      parentRoute: typeof CoffreRoute
    }
  }
}

interface CoffreRouteChildren {
  CoffreAccessRoute: typeof CoffreAccessRoute
  CoffreAccountRoute: typeof CoffreAccountRoute
  CoffreAuditRoute: typeof CoffreAuditRoute
  CoffreSettingsRoute: typeof CoffreSettingsRoute
  CoffreIndexRoute: typeof CoffreIndexRoute
  CoffreTokensTokenRoute: typeof CoffreTokensTokenRoute
  CoffreUsersUserRoute: typeof CoffreUsersUserRoute
  CoffreProjectsIndexRoute: typeof CoffreProjectsIndexRoute
  CoffreTokensIndexRoute: typeof CoffreTokensIndexRoute
  CoffreUsersIndexRoute: typeof CoffreUsersIndexRoute
  CoffreProjectsProjectEnvironmentRoute: typeof CoffreProjectsProjectEnvironmentRoute
  CoffreProjectsProjectIndexRoute: typeof CoffreProjectsProjectIndexRoute
}

const CoffreRouteChildren: CoffreRouteChildren = {
  CoffreAccessRoute: CoffreAccessRoute,
  CoffreAccountRoute: CoffreAccountRoute,
  CoffreAuditRoute: CoffreAuditRoute,
  CoffreSettingsRoute: CoffreSettingsRoute,
  CoffreIndexRoute: CoffreIndexRoute,
  CoffreTokensTokenRoute: CoffreTokensTokenRoute,
  CoffreUsersUserRoute: CoffreUsersUserRoute,
  CoffreProjectsIndexRoute: CoffreProjectsIndexRoute,
  CoffreTokensIndexRoute: CoffreTokensIndexRoute,
  CoffreUsersIndexRoute: CoffreUsersIndexRoute,
  CoffreProjectsProjectEnvironmentRoute: CoffreProjectsProjectEnvironmentRoute,
  CoffreProjectsProjectIndexRoute: CoffreProjectsProjectIndexRoute,
}

const CoffreRouteWithChildren =
  CoffreRoute._addFileChildren(CoffreRouteChildren)

interface SoloRouteChildren {
  SoloLoginRoute: typeof SoloLoginRoute
  SoloUnregisteredRoute: typeof SoloUnregisteredRoute
  SoloApprovalsApprovalRoute: typeof SoloApprovalsApprovalRoute
  SoloAuthDeviceRoute: typeof SoloAuthDeviceRoute
  SoloOauthAuthorizeRoute: typeof SoloOauthAuthorizeRoute
}

const SoloRouteChildren: SoloRouteChildren = {
  SoloLoginRoute: SoloLoginRoute,
  SoloUnregisteredRoute: SoloUnregisteredRoute,
  SoloApprovalsApprovalRoute: SoloApprovalsApprovalRoute,
  SoloAuthDeviceRoute: SoloAuthDeviceRoute,
  SoloOauthAuthorizeRoute: SoloOauthAuthorizeRoute,
}

const SoloRouteWithChildren = SoloRoute._addFileChildren(SoloRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CoffreRoute: CoffreRouteWithChildren,
  SoloRoute: SoloRouteWithChildren,
  LivezRoute: LivezRoute,
  McpRoute: McpRoute,
  ReadyzRoute: ReadyzRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthSplatRoute: AuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
