-- The schema on SQLite. Generated by `pnpm db:generate` from
-- baseline/sqlite.sql and src/schema.sqlite.ts; edit those, not this.

-- @schema

-- The chain starts at sequence 0 from 32 zero bytes, and the heartbeat row
-- is always there to update.
INSERT INTO `audit_chain_head` (`only_row`, `next_seq`, `head_hash`) VALUES (true, 0, zeroblob(32));
--> statement-breakpoint
INSERT INTO `audit_heartbeat` (`only_row`, `last_seq`) VALUES (true, 0);
