-- The schema on Postgres. Generated by `pnpm db:generate` from
-- baseline/postgres.sql and src/schema.ts; edit those, not this.

-- @schema

-- The chain starts at sequence 0 from 32 zero bytes, and the heartbeat row
-- is always there to update.
INSERT INTO audit_chain_head (only_row, next_seq, head_hash)
VALUES (true, 0, decode(repeat('00', 32), 'hex'));
--> statement-breakpoint

INSERT INTO audit_heartbeat (only_row, last_seq)
VALUES (true, 0);
--> statement-breakpoint

-- The audit log only grows, for every login, its owner's included. The
-- grants below already keep the runtime login from changing it; this stops
-- a bug or a careless statement by the owner too, who can still lift it
-- with ALTER TABLE ... DISABLE TRIGGER. What an owner changes anyway, the
-- entries' MACs and chain show.
CREATE FUNCTION audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only' USING ERRCODE = 'insufficient_privilege';
END
$$;
--> statement-breakpoint
CREATE TRIGGER audit_log_no_change BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
--> statement-breakpoint
CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
    FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only();
--> statement-breakpoint

-- Two logins, provisioned outside coffre (their passwords are never ours),
-- each with only the rights of its group:
--
--   coffre_runtime        the server, through coffre_app: read and insert,
--                         UPDATE on named columns only, and never DELETE. A
--                         revoked session, a used device code and a removed
--                         sync key are rows that say so, not gaps.
--   coffre_vault_runtime  the vault, through coffre_vault: its members and
--                         grants, and reading what it decides on.
--
-- Both append to the audit log, each only as its own author (row-level
-- security, below), and neither may change or delete an entry.
DO $$
DECLARE
    name text;
BEGIN
    FOREACH name IN ARRAY ARRAY['coffre_app', 'coffre_vault'] LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = name) THEN
            EXECUTE format('CREATE ROLE %I', name);
        END IF;
    END LOOP;
END
$$;
--> statement-breakpoint

ALTER ROLE coffre_app
    NOLOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
--> statement-breakpoint
ALTER ROLE coffre_vault
    NOLOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
--> statement-breakpoint

DO $$
DECLARE
    name text;
    runtime_role oid;
BEGIN
    FOREACH name IN ARRAY ARRAY['coffre_runtime', 'coffre_vault_runtime'] LOOP
        SELECT oid INTO runtime_role FROM pg_roles WHERE rolname = name;
        IF runtime_role IS NULL THEN
            RAISE EXCEPTION '% must be provisioned before migrations', name;
        END IF;

        IF EXISTS (
            SELECT 1
              FROM pg_roles
             WHERE oid = runtime_role
               AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)
        ) THEN
            RAISE EXCEPTION '% has unsafe role attributes', name;
        END IF;

        IF EXISTS (
            SELECT 1
              FROM pg_shdepend
             WHERE refclassid = 'pg_authid'::regclass
               AND refobjid = runtime_role
               AND deptype = 'o'
        ) THEN
            RAISE EXCEPTION '% owns database objects', name;
        END IF;
    END LOOP;
END
$$;
--> statement-breakpoint

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
    FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public
    FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public
    FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON SCHEMA public
    FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO coffre_app, coffre_vault;
--> statement-breakpoint
GRANT USAGE ON SCHEMA drizzle TO coffre_app, coffre_vault;
--> statement-breakpoint
GRANT SELECT ON drizzle.__drizzle_migrations TO coffre_app, coffre_vault;
--> statement-breakpoint

GRANT SELECT, INSERT ON
    projects,
    environments,
    secrets,
    secret_versions,
    audit_log,
    identities,
    credentials,
    device_authorizations,
    syncs,
    sync_keys
TO coffre_app;
--> statement-breakpoint

GRANT SELECT ON
    audit_chain_head,
    audit_heartbeat,
    vault_members,
    vault_grants
TO coffre_app;
--> statement-breakpoint

GRANT UPDATE (slug, name, archived_at) ON projects TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (slug, name, archived_at) ON environments TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (key, current_version_id, current_version, updated_at, archived_at) ON secrets TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (next_seq, head_hash) ON audit_chain_head TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (last_beat_at, last_seq) ON audit_heartbeat TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (email, last_sign_in_at, revoked_at, revoked_by, auth_mac) ON identities TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (last_used_at, last_used_ip, revoked_at, revoked_by, auth_mac) ON credentials TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (decided_at, decision, generation, principal, consumed_at, auth_mac)
    ON device_authorizations TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (config, credential_secret_id, paused_at, archived_at, lease_until,
              last_run_at, last_status, last_error)
    ON syncs TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (secret_version_id, pushed_at, removed_at) ON sync_keys TO coffre_app;
--> statement-breakpoint

-- The vault reads what it decides on and the log it chains to, and writes
-- its members and grants. A revoked grant is deleted: the log keeps it.
GRANT SELECT ON
    projects,
    environments,
    secrets,
    secret_versions,
    audit_chain_head
TO coffre_vault;
--> statement-breakpoint
GRANT SELECT, INSERT ON audit_log TO coffre_vault;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE (status, owner, generation, status_changed_at, status_changed_by)
    ON vault_members TO coffre_vault;
--> statement-breakpoint
GRANT SELECT, INSERT, DELETE ON vault_grants TO coffre_vault;
--> statement-breakpoint
GRANT UPDATE (next_seq, head_hash) ON audit_chain_head TO coffre_vault;
--> statement-breakpoint

REVOKE DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public FROM coffre_app;
--> statement-breakpoint
REVOKE TRUNCATE ON ALL TABLES IN SCHEMA public FROM coffre_vault;
--> statement-breakpoint
REVOKE UPDATE ON audit_log, secret_versions FROM coffre_app, coffre_vault;
--> statement-breakpoint
REVOKE CREATE ON SCHEMA public FROM PUBLIC, coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint

-- Each login appends only as its own author. Its MAC is still what proves
-- who wrote an entry: the table's owner passes these policies, as owners do.
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY audit_log_read ON audit_log FOR SELECT TO coffre_app, coffre_vault USING (true);
--> statement-breakpoint
CREATE POLICY audit_log_app_appends ON audit_log FOR INSERT TO coffre_app WITH CHECK (author = 'app');
--> statement-breakpoint
CREATE POLICY audit_log_vault_appends ON audit_log FOR INSERT TO coffre_vault WITH CHECK (author = 'vault');
--> statement-breakpoint

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON TABLES FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON SEQUENCES FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON ROUTINES FROM coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime;
--> statement-breakpoint

-- Each login is a member of its own group and of nothing else.
DO $$
DECLARE
    login record;
    membership record;
BEGIN
    EXECUTE format(
        'REVOKE CREATE, TEMPORARY ON DATABASE %I FROM PUBLIC, coffre_app, coffre_runtime, coffre_vault, coffre_vault_runtime',
        current_database()
    );

    FOR login IN
        SELECT * FROM (VALUES ('coffre_runtime', 'coffre_app'), ('coffre_vault_runtime', 'coffre_vault')) AS logins (name, grp)
    LOOP
        FOR membership IN
            SELECT granted.rolname
              FROM pg_auth_members member_of
              JOIN pg_roles member ON member.oid = member_of.member
              JOIN pg_roles granted ON granted.oid = member_of.roleid
             WHERE member.rolname = login.name
               AND granted.rolname <> login.grp
        LOOP
            EXECUTE format('REVOKE %I FROM %I', membership.rolname, login.name);
        END LOOP;
    END LOOP;
END
$$;
--> statement-breakpoint

GRANT coffre_app TO coffre_runtime WITH ADMIN FALSE, INHERIT TRUE, SET FALSE;
--> statement-breakpoint
GRANT coffre_vault TO coffre_vault_runtime WITH ADMIN FALSE, INHERIT TRUE, SET FALSE;
