-- The schema on SQLite. Generated by `pnpm db:generate` from
-- baseline/sqlite.sql and src/schema.sqlite.ts; edit those, not this.

-- @schema

-- The chain starts at sequence 0 from 32 zero bytes.
INSERT INTO `audit_chain_head` (`only_row`, `next_seq`, `head_hash`) VALUES (true, 0, zeroblob(32));
--> statement-breakpoint

-- The audit log only grows: no statement may change or delete an entry.
-- What gets past this anyway, the entries' MACs and chain show.
-- REPLACE can delete without firing DELETE triggers, so refuse it before insert.
CREATE TRIGGER `audit_log_no_replace` BEFORE INSERT ON `audit_log`
WHEN EXISTS (SELECT 1 FROM `audit_log` WHERE `seq` = NEW.`seq`)
BEGIN
    SELECT RAISE(ABORT, 'audit_log is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER `audit_log_no_update` BEFORE UPDATE ON `audit_log`
BEGIN
    SELECT RAISE(ABORT, 'audit_log is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER `audit_log_no_delete` BEFORE DELETE ON `audit_log`
BEGIN
    SELECT RAISE(ABORT, 'audit_log is append-only');
END;
