import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

/**
 * Write src/migrations.ts from migrations/, which drizzle-kit generates from
 * src/schema.ts (custom migrations are written by hand there). A Worker has
 * no file system, so the migrations travel inside the code as a module, in
 * the shape Drizzle's Durable Object migrator reads.
 *
 * `pnpm --dir packages/vault generate` runs drizzle-kit, then this.
 */

const root = fileURLToPath(new URL('..', import.meta.url));

type Journal = { entries: { idx: number; tag: string }[] };

export async function embeddedMigrations(): Promise<string> {
  const journal = JSON.parse(await readFile(`${root}migrations/meta/_journal.json`, 'utf8')) as Journal;
  const migrations: Record<string, string> = {};
  for (const entry of journal.entries) {
    migrations[`m${String(entry.idx).padStart(4, '0')}`] = await readFile(`${root}migrations/${entry.tag}.sql`, 'utf8');
  }
  return [
    '// Generated by `pnpm --dir packages/vault generate` from migrations/; edit those, not this.',
    '',
    `export default ${JSON.stringify({ journal, migrations }, null, 2)};`,
    '',
  ].join('\n');
}

if (import.meta.main) {
  await writeFile(`${root}src/migrations.ts`, await embeddedMigrations());
}
