// Generated by `pnpm --dir packages/vault generate` from migrations/; edit those, not this.

export default {
  "journal": {
    "version": "7",
    "dialect": "sqlite",
    "entries": [
      {
        "idx": 0,
        "version": "6",
        "when": 1790620523973,
        "tag": "0000_store",
        "breakpoints": true
      },
      {
        "idx": 1,
        "version": "6",
        "when": 1790620524467,
        "tag": "0001_append_only",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `checkpoints` (\n\t`seq` integer PRIMARY KEY NOT NULL,\n\t`head_hash` text NOT NULL,\n\t`signed_at` integer NOT NULL,\n\t`key_id` text NOT NULL,\n\t`signature` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `grants` (\n\t`principal` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`environment_id` text,\n\t`role` text NOT NULL,\n\t`expires_at` integer,\n\t`granted_at` integer NOT NULL,\n\t`granted_by` text NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `grants_on_project` ON `grants` (`principal`,`project_id`) WHERE \"grants\".\"environment_id\" IS NULL;--> statement-breakpoint\nCREATE UNIQUE INDEX `grants_on_environment` ON `grants` (`principal`,`environment_id`) WHERE \"grants\".\"environment_id\" IS NOT NULL;--> statement-breakpoint\nCREATE TABLE `log` (\n\t`seq` integer PRIMARY KEY NOT NULL,\n\t`at` integer NOT NULL,\n\t`actor` text NOT NULL,\n\t`action` text NOT NULL,\n\t`outcome` text NOT NULL,\n\t`code` text,\n\t`subject` text,\n\t`detail` text NOT NULL,\n\t`prev_hash` text NOT NULL,\n\t`hash` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `log_by_actor` ON `log` (`actor`,`action`,`at`);--> statement-breakpoint\nCREATE TABLE `principals` (\n\t`principal` text PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`owner` integer DEFAULT false NOT NULL,\n\t`since` integer NOT NULL,\n\t`by` text NOT NULL\n);\n",
    "m0001": "-- The log is append-only. The vault's code never updates or deletes a row;\n-- these make a bug that tried fail instead of rewriting history.\nCREATE TRIGGER `log_no_update` BEFORE UPDATE ON `log`\nBEGIN\n    SELECT RAISE(ABORT, 'the vault log is append-only');\nEND;\n--> statement-breakpoint\nCREATE TRIGGER `log_no_delete` BEFORE DELETE ON `log`\nBEGIN\n    SELECT RAISE(ABORT, 'the vault log is append-only');\nEND;\n"
  }
};
