/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoffreRouteImport } from './routes/_coffre'
import { Route as SoloRouteImport } from './routes/_solo'
import { Route as LivezRouteImport } from './routes/livez'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known.$'
import { Route as CoffreIndexRouteImport } from './routes/_coffre/index'
import { Route as CoffreAccessRouteImport } from './routes/_coffre/access'
import { Route as CoffreAccountRouteImport } from './routes/_coffre/account'
import { Route as CoffreAuditRouteImport } from './routes/_coffre/audit'
import { Route as CoffreSettingsRouteImport } from './routes/_coffre/settings'
import { Route as SoloLoginRouteImport } from './routes/_solo/login'
import { Route as SoloUnregisteredRouteImport } from './routes/_solo/unregistered'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as CoffreProjectsIndexRouteImport } from './routes/_coffre/projects.index'
import { Route as CoffreProjectsProjectRouteImport } from './routes/_coffre/projects.$project'
import { Route as CoffreServiceAccountsIndexRouteImport } from './routes/_coffre/service-accounts.index'
import { Route as CoffreServiceAccountsAccountRouteImport } from './routes/_coffre/service-accounts.$account'
import { Route as CoffreUsersIndexRouteImport } from './routes/_coffre/users.index'
import { Route as CoffreUsersUserRouteImport } from './routes/_coffre/users.$user'
import { Route as SoloApprovalsApprovalRouteImport } from './routes/_solo/approvals.$approval'
import { Route as SoloAuthDeviceRouteImport } from './routes/_solo/auth.device'
import { Route as SoloOauthAuthorizeRouteImport } from './routes/_solo/oauth.authorize'
import { Route as CoffreProjectsProjectIndexRouteImport } from './routes/_coffre/projects.$project.index'
import { Route as CoffreProjectsProjectServiceAccountsRouteImport } from './routes/_coffre/projects.$project.service-accounts'
import { Route as CoffreProjectsProjectSettingsRouteImport } from './routes/_coffre/projects.$project.settings'
import { Route as CoffreProjectsProjectUsersRouteImport } from './routes/_coffre/projects.$project.users'
import { Route as CoffreProjectsProjectEnvironmentRouteImport } from './routes/_coffre/projects.$project_.$environment'
import { Route as CoffreServiceAccountsAccountIndexRouteImport } from './routes/_coffre/service-accounts.$account.index'
import { Route as CoffreServiceAccountsAccountAccessRouteImport } from './routes/_coffre/service-accounts.$account.access'
import { Route as CoffreServiceAccountsAccountActivityRouteImport } from './routes/_coffre/service-accounts.$account.activity'
import { Route as CoffreUsersUserIndexRouteImport } from './routes/_coffre/users.$user.index'
import { Route as CoffreUsersUserActivityRouteImport } from './routes/_coffre/users.$user.activity'

const CoffreRoute = CoffreRouteImport.update({
  id: '/_coffre',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/_solo',
  getParentRoute: () => rootRouteImport,
} as any)
const LivezRoute = LivezRouteImport.update({
  id: '/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffreIndexRoute = CoffreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAccessRoute = CoffreAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAccountRoute = CoffreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreAuditRoute = CoffreAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreSettingsRoute = CoffreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoffreRoute,
} as any)
const SoloLoginRoute = SoloLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SoloRoute,
} as any)
const SoloUnregisteredRoute = SoloUnregisteredRouteImport.update({
  id: '/unregistered',
  path: '/unregistered',
  getParentRoute: () => SoloRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffreProjectsIndexRoute = CoffreProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreProjectsProjectRoute = CoffreProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreServiceAccountsIndexRoute =
  CoffreServiceAccountsIndexRouteImport.update({
    id: '/service-accounts/',
    path: '/service-accounts/',
    getParentRoute: () => CoffreRoute,
  } as any)
const CoffreServiceAccountsAccountRoute =
  CoffreServiceAccountsAccountRouteImport.update({
    id: '/service-accounts/$account',
    path: '/service-accounts/$account',
    getParentRoute: () => CoffreRoute,
  } as any)
const CoffreUsersIndexRoute = CoffreUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => CoffreRoute,
} as any)
const CoffreUsersUserRoute = CoffreUsersUserRouteImport.update({
  id: '/users/$user',
  path: '/users/$user',
  getParentRoute: () => CoffreRoute,
} as any)
const SoloApprovalsApprovalRoute = SoloApprovalsApprovalRouteImport.update({
  id: '/approvals/$approval',
  path: '/approvals/$approval',
  getParentRoute: () => SoloRoute,
} as any)
const SoloAuthDeviceRoute = SoloAuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => SoloRoute,
} as any)
const SoloOauthAuthorizeRoute = SoloOauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => SoloRoute,
} as any)
const CoffreProjectsProjectIndexRoute =
  CoffreProjectsProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoffreProjectsProjectRoute,
  } as any)
const CoffreProjectsProjectServiceAccountsRoute =
  CoffreProjectsProjectServiceAccountsRouteImport.update({
    id: '/service-accounts',
    path: '/service-accounts',
    getParentRoute: () => CoffreProjectsProjectRoute,
  } as any)
const CoffreProjectsProjectSettingsRoute =
  CoffreProjectsProjectSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CoffreProjectsProjectRoute,
  } as any)
const CoffreProjectsProjectUsersRoute =
  CoffreProjectsProjectUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => CoffreProjectsProjectRoute,
  } as any)
const CoffreProjectsProjectEnvironmentRoute =
  CoffreProjectsProjectEnvironmentRouteImport.update({
    id: '/projects/$project_/$environment',
    path: '/projects/$project/$environment',
    getParentRoute: () => CoffreRoute,
  } as any)
const CoffreServiceAccountsAccountIndexRoute =
  CoffreServiceAccountsAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoffreServiceAccountsAccountRoute,
  } as any)
const CoffreServiceAccountsAccountAccessRoute =
  CoffreServiceAccountsAccountAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => CoffreServiceAccountsAccountRoute,
  } as any)
const CoffreServiceAccountsAccountActivityRoute =
  CoffreServiceAccountsAccountActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => CoffreServiceAccountsAccountRoute,
  } as any)
const CoffreUsersUserIndexRoute = CoffreUsersUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoffreUsersUserRoute,
} as any)
const CoffreUsersUserActivityRoute = CoffreUsersUserActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => CoffreUsersUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CoffreIndexRoute
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/access': typeof CoffreAccessRoute
  '/account': typeof CoffreAccountRoute
  '/audit': typeof CoffreAuditRoute
  '/settings': typeof CoffreSettingsRoute
  '/login': typeof SoloLoginRoute
  '/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/projects/$project': typeof CoffreProjectsProjectRouteWithChildren
  '/service-accounts/$account': typeof CoffreServiceAccountsAccountRouteWithChildren
  '/users/$user': typeof CoffreUsersUserRouteWithChildren
  '/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/auth/device': typeof SoloAuthDeviceRoute
  '/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/projects/': typeof CoffreProjectsIndexRoute
  '/service-accounts/': typeof CoffreServiceAccountsIndexRoute
  '/users/': typeof CoffreUsersIndexRoute
  '/projects/$project/service-accounts': typeof CoffreProjectsProjectServiceAccountsRoute
  '/projects/$project/settings': typeof CoffreProjectsProjectSettingsRoute
  '/projects/$project/users': typeof CoffreProjectsProjectUsersRoute
  '/projects/$project/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/service-accounts/$account/access': typeof CoffreServiceAccountsAccountAccessRoute
  '/service-accounts/$account/activity': typeof CoffreServiceAccountsAccountActivityRoute
  '/users/$user/activity': typeof CoffreUsersUserActivityRoute
  '/projects/$project/': typeof CoffreProjectsProjectIndexRoute
  '/service-accounts/$account/': typeof CoffreServiceAccountsAccountIndexRoute
  '/users/$user/': typeof CoffreUsersUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CoffreIndexRoute
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/access': typeof CoffreAccessRoute
  '/account': typeof CoffreAccountRoute
  '/audit': typeof CoffreAuditRoute
  '/settings': typeof CoffreSettingsRoute
  '/login': typeof SoloLoginRoute
  '/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/auth/device': typeof SoloAuthDeviceRoute
  '/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/projects': typeof CoffreProjectsIndexRoute
  '/service-accounts': typeof CoffreServiceAccountsIndexRoute
  '/users': typeof CoffreUsersIndexRoute
  '/projects/$project/service-accounts': typeof CoffreProjectsProjectServiceAccountsRoute
  '/projects/$project/settings': typeof CoffreProjectsProjectSettingsRoute
  '/projects/$project/users': typeof CoffreProjectsProjectUsersRoute
  '/projects/$project/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/service-accounts/$account/access': typeof CoffreServiceAccountsAccountAccessRoute
  '/service-accounts/$account/activity': typeof CoffreServiceAccountsAccountActivityRoute
  '/users/$user/activity': typeof CoffreUsersUserActivityRoute
  '/projects/$project': typeof CoffreProjectsProjectIndexRoute
  '/service-accounts/$account': typeof CoffreServiceAccountsAccountIndexRoute
  '/users/$user': typeof CoffreUsersUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_coffre': typeof CoffreRouteWithChildren
  '/_solo': typeof SoloRouteWithChildren
  '/livez': typeof LivezRoute
  '/mcp': typeof McpRoute
  '/readyz': typeof ReadyzRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_coffre/access': typeof CoffreAccessRoute
  '/_coffre/account': typeof CoffreAccountRoute
  '/_coffre/audit': typeof CoffreAuditRoute
  '/_coffre/settings': typeof CoffreSettingsRoute
  '/_solo/login': typeof SoloLoginRoute
  '/_solo/unregistered': typeof SoloUnregisteredRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$': typeof AuthSplatRoute
  '/_coffre/': typeof CoffreIndexRoute
  '/_coffre/projects/$project': typeof CoffreProjectsProjectRouteWithChildren
  '/_coffre/service-accounts/$account': typeof CoffreServiceAccountsAccountRouteWithChildren
  '/_coffre/users/$user': typeof CoffreUsersUserRouteWithChildren
  '/_solo/approvals/$approval': typeof SoloApprovalsApprovalRoute
  '/_solo/auth/device': typeof SoloAuthDeviceRoute
  '/_solo/oauth/authorize': typeof SoloOauthAuthorizeRoute
  '/_coffre/projects/': typeof CoffreProjectsIndexRoute
  '/_coffre/service-accounts/': typeof CoffreServiceAccountsIndexRoute
  '/_coffre/users/': typeof CoffreUsersIndexRoute
  '/_coffre/projects/$project/service-accounts': typeof CoffreProjectsProjectServiceAccountsRoute
  '/_coffre/projects/$project/settings': typeof CoffreProjectsProjectSettingsRoute
  '/_coffre/projects/$project/users': typeof CoffreProjectsProjectUsersRoute
  '/_coffre/projects/$project_/$environment': typeof CoffreProjectsProjectEnvironmentRoute
  '/_coffre/service-accounts/$account/access': typeof CoffreServiceAccountsAccountAccessRoute
  '/_coffre/service-accounts/$account/activity': typeof CoffreServiceAccountsAccountActivityRoute
  '/_coffre/users/$user/activity': typeof CoffreUsersUserActivityRoute
  '/_coffre/projects/$project/': typeof CoffreProjectsProjectIndexRoute
  '/_coffre/service-accounts/$account/': typeof CoffreServiceAccountsAccountIndexRoute
  '/_coffre/users/$user/': typeof CoffreUsersUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/settings'
    | '/login'
    | '/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/projects/$project'
    | '/service-accounts/$account'
    | '/users/$user'
    | '/approvals/$approval'
    | '/auth/device'
    | '/oauth/authorize'
    | '/projects/'
    | '/service-accounts/'
    | '/users/'
    | '/projects/$project/service-accounts'
    | '/projects/$project/settings'
    | '/projects/$project/users'
    | '/projects/$project/$environment'
    | '/service-accounts/$account/access'
    | '/service-accounts/$account/activity'
    | '/users/$user/activity'
    | '/projects/$project/'
    | '/service-accounts/$account/'
    | '/users/$user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/settings'
    | '/login'
    | '/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/approvals/$approval'
    | '/auth/device'
    | '/oauth/authorize'
    | '/projects'
    | '/service-accounts'
    | '/users'
    | '/projects/$project/service-accounts'
    | '/projects/$project/settings'
    | '/projects/$project/users'
    | '/projects/$project/$environment'
    | '/service-accounts/$account/access'
    | '/service-accounts/$account/activity'
    | '/users/$user/activity'
    | '/projects/$project'
    | '/service-accounts/$account'
    | '/users/$user'
  id:
    | '__root__'
    | '/_coffre'
    | '/_solo'
    | '/livez'
    | '/mcp'
    | '/readyz'
    | '/.well-known/$'
    | '/_coffre/access'
    | '/_coffre/account'
    | '/_coffre/audit'
    | '/_coffre/settings'
    | '/_solo/login'
    | '/_solo/unregistered'
    | '/api/$'
    | '/auth/$'
    | '/_coffre/'
    | '/_coffre/projects/$project'
    | '/_coffre/service-accounts/$account'
    | '/_coffre/users/$user'
    | '/_solo/approvals/$approval'
    | '/_solo/auth/device'
    | '/_solo/oauth/authorize'
    | '/_coffre/projects/'
    | '/_coffre/service-accounts/'
    | '/_coffre/users/'
    | '/_coffre/projects/$project/service-accounts'
    | '/_coffre/projects/$project/settings'
    | '/_coffre/projects/$project/users'
    | '/_coffre/projects/$project_/$environment'
    | '/_coffre/service-accounts/$account/access'
    | '/_coffre/service-accounts/$account/activity'
    | '/_coffre/users/$user/activity'
    | '/_coffre/projects/$project/'
    | '/_coffre/service-accounts/$account/'
    | '/_coffre/users/$user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoffreRoute: typeof CoffreRouteWithChildren
  SoloRoute: typeof SoloRouteWithChildren
  LivezRoute: typeof LivezRoute
  McpRoute: typeof McpRoute
  ReadyzRoute: typeof ReadyzRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSplatRoute: typeof AuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_coffre': {
      id: '/_coffre'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoffreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_solo': {
      id: '/_solo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livez': {
      id: '/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof LivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coffre/': {
      id: '/_coffre/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CoffreIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/access': {
      id: '/_coffre/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof CoffreAccessRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/account': {
      id: '/_coffre/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof CoffreAccountRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/audit': {
      id: '/_coffre/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof CoffreAuditRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/settings': {
      id: '/_coffre/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CoffreSettingsRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_solo/login': {
      id: '/_solo/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SoloLoginRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/unregistered': {
      id: '/_solo/unregistered'
      path: '/unregistered'
      fullPath: '/unregistered'
      preLoaderRoute: typeof SoloUnregisteredRouteImport
      parentRoute: typeof SoloRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coffre/projects/': {
      id: '/_coffre/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof CoffreProjectsIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/projects/$project': {
      id: '/_coffre/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof CoffreProjectsProjectRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/service-accounts/': {
      id: '/_coffre/service-accounts/'
      path: '/service-accounts'
      fullPath: '/service-accounts/'
      preLoaderRoute: typeof CoffreServiceAccountsIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/service-accounts/$account': {
      id: '/_coffre/service-accounts/$account'
      path: '/service-accounts/$account'
      fullPath: '/service-accounts/$account'
      preLoaderRoute: typeof CoffreServiceAccountsAccountRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/users/': {
      id: '/_coffre/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof CoffreUsersIndexRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/users/$user': {
      id: '/_coffre/users/$user'
      path: '/users/$user'
      fullPath: '/users/$user'
      preLoaderRoute: typeof CoffreUsersUserRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_solo/approvals/$approval': {
      id: '/_solo/approvals/$approval'
      path: '/approvals/$approval'
      fullPath: '/approvals/$approval'
      preLoaderRoute: typeof SoloApprovalsApprovalRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/auth/device': {
      id: '/_solo/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof SoloAuthDeviceRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_solo/oauth/authorize': {
      id: '/_solo/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof SoloOauthAuthorizeRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_coffre/projects/$project/': {
      id: '/_coffre/projects/$project/'
      path: '/'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof CoffreProjectsProjectIndexRouteImport
      parentRoute: typeof CoffreProjectsProjectRoute
    }
    '/_coffre/projects/$project/service-accounts': {
      id: '/_coffre/projects/$project/service-accounts'
      path: '/service-accounts'
      fullPath: '/projects/$project/service-accounts'
      preLoaderRoute: typeof CoffreProjectsProjectServiceAccountsRouteImport
      parentRoute: typeof CoffreProjectsProjectRoute
    }
    '/_coffre/projects/$project/settings': {
      id: '/_coffre/projects/$project/settings'
      path: '/settings'
      fullPath: '/projects/$project/settings'
      preLoaderRoute: typeof CoffreProjectsProjectSettingsRouteImport
      parentRoute: typeof CoffreProjectsProjectRoute
    }
    '/_coffre/projects/$project/users': {
      id: '/_coffre/projects/$project/users'
      path: '/users'
      fullPath: '/projects/$project/users'
      preLoaderRoute: typeof CoffreProjectsProjectUsersRouteImport
      parentRoute: typeof CoffreProjectsProjectRoute
    }
    '/_coffre/projects/$project_/$environment': {
      id: '/_coffre/projects/$project_/$environment'
      path: '/projects/$project/$environment'
      fullPath: '/projects/$project/$environment'
      preLoaderRoute: typeof CoffreProjectsProjectEnvironmentRouteImport
      parentRoute: typeof CoffreRoute
    }
    '/_coffre/service-accounts/$account/': {
      id: '/_coffre/service-accounts/$account/'
      path: '/'
      fullPath: '/service-accounts/$account/'
      preLoaderRoute: typeof CoffreServiceAccountsAccountIndexRouteImport
      parentRoute: typeof CoffreServiceAccountsAccountRoute
    }
    '/_coffre/service-accounts/$account/access': {
      id: '/_coffre/service-accounts/$account/access'
      path: '/access'
      fullPath: '/service-accounts/$account/access'
      preLoaderRoute: typeof CoffreServiceAccountsAccountAccessRouteImport
      parentRoute: typeof CoffreServiceAccountsAccountRoute
    }
    '/_coffre/service-accounts/$account/activity': {
      id: '/_coffre/service-accounts/$account/activity'
      path: '/activity'
      fullPath: '/service-accounts/$account/activity'
      preLoaderRoute: typeof CoffreServiceAccountsAccountActivityRouteImport
      parentRoute: typeof CoffreServiceAccountsAccountRoute
    }
    '/_coffre/users/$user/': {
      id: '/_coffre/users/$user/'
      path: '/'
      fullPath: '/users/$user/'
      preLoaderRoute: typeof CoffreUsersUserIndexRouteImport
      parentRoute: typeof CoffreUsersUserRoute
    }
    '/_coffre/users/$user/activity': {
      id: '/_coffre/users/$user/activity'
      path: '/activity'
      fullPath: '/users/$user/activity'
      preLoaderRoute: typeof CoffreUsersUserActivityRouteImport
      parentRoute: typeof CoffreUsersUserRoute
    }
  }
}

interface CoffreProjectsProjectRouteChildren {
  CoffreProjectsProjectServiceAccountsRoute: typeof CoffreProjectsProjectServiceAccountsRoute
  CoffreProjectsProjectSettingsRoute: typeof CoffreProjectsProjectSettingsRoute
  CoffreProjectsProjectUsersRoute: typeof CoffreProjectsProjectUsersRoute
  CoffreProjectsProjectIndexRoute: typeof CoffreProjectsProjectIndexRoute
}

const CoffreProjectsProjectRouteChildren: CoffreProjectsProjectRouteChildren = {
  CoffreProjectsProjectServiceAccountsRoute:
    CoffreProjectsProjectServiceAccountsRoute,
  CoffreProjectsProjectSettingsRoute: CoffreProjectsProjectSettingsRoute,
  CoffreProjectsProjectUsersRoute: CoffreProjectsProjectUsersRoute,
  CoffreProjectsProjectIndexRoute: CoffreProjectsProjectIndexRoute,
}

const CoffreProjectsProjectRouteWithChildren =
  CoffreProjectsProjectRoute._addFileChildren(
    CoffreProjectsProjectRouteChildren,
  )

interface CoffreServiceAccountsAccountRouteChildren {
  CoffreServiceAccountsAccountAccessRoute: typeof CoffreServiceAccountsAccountAccessRoute
  CoffreServiceAccountsAccountActivityRoute: typeof CoffreServiceAccountsAccountActivityRoute
  CoffreServiceAccountsAccountIndexRoute: typeof CoffreServiceAccountsAccountIndexRoute
}

const CoffreServiceAccountsAccountRouteChildren: CoffreServiceAccountsAccountRouteChildren =
  {
    CoffreServiceAccountsAccountAccessRoute:
      CoffreServiceAccountsAccountAccessRoute,
    CoffreServiceAccountsAccountActivityRoute:
      CoffreServiceAccountsAccountActivityRoute,
    CoffreServiceAccountsAccountIndexRoute:
      CoffreServiceAccountsAccountIndexRoute,
  }

const CoffreServiceAccountsAccountRouteWithChildren =
  CoffreServiceAccountsAccountRoute._addFileChildren(
    CoffreServiceAccountsAccountRouteChildren,
  )

interface CoffreUsersUserRouteChildren {
  CoffreUsersUserActivityRoute: typeof CoffreUsersUserActivityRoute
  CoffreUsersUserIndexRoute: typeof CoffreUsersUserIndexRoute
}

const CoffreUsersUserRouteChildren: CoffreUsersUserRouteChildren = {
  CoffreUsersUserActivityRoute: CoffreUsersUserActivityRoute,
  CoffreUsersUserIndexRoute: CoffreUsersUserIndexRoute,
}

const CoffreUsersUserRouteWithChildren = CoffreUsersUserRoute._addFileChildren(
  CoffreUsersUserRouteChildren,
)

interface CoffreRouteChildren {
  CoffreAccessRoute: typeof CoffreAccessRoute
  CoffreAccountRoute: typeof CoffreAccountRoute
  CoffreAuditRoute: typeof CoffreAuditRoute
  CoffreSettingsRoute: typeof CoffreSettingsRoute
  CoffreIndexRoute: typeof CoffreIndexRoute
  CoffreProjectsProjectRoute: typeof CoffreProjectsProjectRouteWithChildren
  CoffreServiceAccountsAccountRoute: typeof CoffreServiceAccountsAccountRouteWithChildren
  CoffreUsersUserRoute: typeof CoffreUsersUserRouteWithChildren
  CoffreProjectsIndexRoute: typeof CoffreProjectsIndexRoute
  CoffreServiceAccountsIndexRoute: typeof CoffreServiceAccountsIndexRoute
  CoffreUsersIndexRoute: typeof CoffreUsersIndexRoute
  CoffreProjectsProjectEnvironmentRoute: typeof CoffreProjectsProjectEnvironmentRoute
}

const CoffreRouteChildren: CoffreRouteChildren = {
  CoffreAccessRoute: CoffreAccessRoute,
  CoffreAccountRoute: CoffreAccountRoute,
  CoffreAuditRoute: CoffreAuditRoute,
  CoffreSettingsRoute: CoffreSettingsRoute,
  CoffreIndexRoute: CoffreIndexRoute,
  CoffreProjectsProjectRoute: CoffreProjectsProjectRouteWithChildren,
  CoffreServiceAccountsAccountRoute:
    CoffreServiceAccountsAccountRouteWithChildren,
  CoffreUsersUserRoute: CoffreUsersUserRouteWithChildren,
  CoffreProjectsIndexRoute: CoffreProjectsIndexRoute,
  CoffreServiceAccountsIndexRoute: CoffreServiceAccountsIndexRoute,
  CoffreUsersIndexRoute: CoffreUsersIndexRoute,
  CoffreProjectsProjectEnvironmentRoute: CoffreProjectsProjectEnvironmentRoute,
}

const CoffreRouteWithChildren =
  CoffreRoute._addFileChildren(CoffreRouteChildren)

interface SoloRouteChildren {
  SoloLoginRoute: typeof SoloLoginRoute
  SoloUnregisteredRoute: typeof SoloUnregisteredRoute
  SoloApprovalsApprovalRoute: typeof SoloApprovalsApprovalRoute
  SoloAuthDeviceRoute: typeof SoloAuthDeviceRoute
  SoloOauthAuthorizeRoute: typeof SoloOauthAuthorizeRoute
}

const SoloRouteChildren: SoloRouteChildren = {
  SoloLoginRoute: SoloLoginRoute,
  SoloUnregisteredRoute: SoloUnregisteredRoute,
  SoloApprovalsApprovalRoute: SoloApprovalsApprovalRoute,
  SoloAuthDeviceRoute: SoloAuthDeviceRoute,
  SoloOauthAuthorizeRoute: SoloOauthAuthorizeRoute,
}

const SoloRouteWithChildren = SoloRoute._addFileChildren(SoloRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CoffreRoute: CoffreRouteWithChildren,
  SoloRoute: SoloRouteWithChildren,
  LivezRoute: LivezRoute,
  McpRoute: McpRoute,
  ReadyzRoute: ReadyzRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthSplatRoute: AuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
