-- The schema on MySQL. Generated by `pnpm db:generate` from
-- baseline/mysql.sql and src/schema.mysql.ts; edit those, not this.

-- Compare strings byte for byte, as Postgres does: API_KEY and api_key are
-- two secrets, and a slug check is case-sensitive.
ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
--> statement-breakpoint

-- @schema

-- The chain starts at sequence 0 from 32 zero bytes, and the heartbeat row
-- is always there to update.
INSERT INTO `audit_chain_head` (`only_row`, `next_seq`, `head_hash`) VALUES (true, 0, UNHEX(REPEAT('00', 32)));
--> statement-breakpoint
INSERT INTO `audit_heartbeat` (`only_row`, `last_seq`) VALUES (true, 0);
