-- The schema on Postgres. Generated by `pnpm db:generate` from
-- baseline/postgres.sql and src/schema.ts; edit those, not this.

-- @schema

-- The chain starts at sequence 0 from 32 zero bytes, and the heartbeat row
-- is always there to update.
INSERT INTO audit_chain_head (only_row, next_seq, head_hash)
VALUES (true, 0, decode(repeat('00', 32), 'hex'));
--> statement-breakpoint

INSERT INTO audit_heartbeat (only_row, last_seq)
VALUES (true, 0);
--> statement-breakpoint

-- The server connects as coffre_runtime, a login provisioned outside
-- coffre (its password is never ours), whose only rights come from
-- coffre_app: read and insert, UPDATE on named columns only, and never
-- DELETE. A revoked session, a used device code and a removed sync key are
-- rows that say so, not gaps; the audit log and secret versions are never
-- updated at all.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'coffre_app') THEN
        CREATE ROLE coffre_app;
    END IF;
END
$$;
--> statement-breakpoint

ALTER ROLE coffre_app
    NOLOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
--> statement-breakpoint

DO $$
DECLARE
    runtime_role oid;
BEGIN
    SELECT oid INTO runtime_role FROM pg_roles WHERE rolname = 'coffre_runtime';
    IF runtime_role IS NULL THEN
        RAISE EXCEPTION 'coffre_runtime must be provisioned before migrations';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_roles
         WHERE oid = runtime_role
           AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)
    ) THEN
        RAISE EXCEPTION 'coffre_runtime has unsafe role attributes';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_shdepend
         WHERE refclassid = 'pg_authid'::regclass
           AND refobjid = runtime_role
           AND deptype = 'o'
    ) THEN
        RAISE EXCEPTION 'coffre_runtime owns database objects';
    END IF;
END
$$;
--> statement-breakpoint

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM coffre_app, coffre_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM coffre_app, coffre_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public FROM coffre_app, coffre_runtime;
--> statement-breakpoint
REVOKE ALL PRIVILEGES ON SCHEMA public FROM coffre_app, coffre_runtime;
--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO coffre_app;
--> statement-breakpoint
GRANT USAGE ON SCHEMA drizzle TO coffre_app;
--> statement-breakpoint
GRANT SELECT ON drizzle.__drizzle_migrations TO coffre_app;
--> statement-breakpoint

GRANT SELECT, INSERT ON
    projects,
    environments,
    secrets,
    secret_versions,
    principals,
    audit_log,
    identities,
    credentials,
    device_authorizations,
    syncs,
    sync_keys
TO coffre_app;
--> statement-breakpoint

GRANT SELECT ON
    audit_chain_head,
    audit_heartbeat
TO coffre_app;
--> statement-breakpoint

GRANT UPDATE (slug, name, archived_at) ON projects TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (slug, name, archived_at) ON environments TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (key, current_version_id, current_version, updated_at, archived_at) ON secrets TO coffre_app;
--> statement-breakpoint
-- Never changed, but SELECT ... FOR UPDATE needs UPDATE on some column, and
-- sign-in and removal lock the directory row while they ask the vault.
GRANT UPDATE (created_by) ON principals TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (next_seq, head_hash, updated_at) ON audit_chain_head TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (last_beat_at, last_seq) ON audit_heartbeat TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (email, last_sign_in_at, revoked_at, revoked_by) ON identities TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (last_used_at, last_used_ip, revoked_at, revoked_by) ON credentials TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (decided_at, decision, principal_type, principal_id, consumed_at)
    ON device_authorizations TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (config, credential_secret_id, paused_at, archived_at, lease_until,
              last_run_at, last_status, last_error)
    ON syncs TO coffre_app;
--> statement-breakpoint
GRANT UPDATE (secret_version_id, pushed_at, removed_at) ON sync_keys TO coffre_app;
--> statement-breakpoint

REVOKE DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public FROM coffre_app;
--> statement-breakpoint
REVOKE UPDATE ON audit_log, secret_versions FROM coffre_app;
--> statement-breakpoint
REVOKE CREATE ON SCHEMA public FROM PUBLIC, coffre_app, coffre_runtime;
--> statement-breakpoint

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON TABLES FROM coffre_app, coffre_runtime;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON SEQUENCES FROM coffre_app, coffre_runtime;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL PRIVILEGES ON ROUTINES FROM coffre_app, coffre_runtime;
--> statement-breakpoint

DO $$
DECLARE
    membership record;
BEGIN
    EXECUTE format(
        'REVOKE CREATE, TEMPORARY ON DATABASE %I FROM PUBLIC, coffre_app, coffre_runtime',
        current_database()
    );

    FOR membership IN
        SELECT granted.rolname
          FROM pg_auth_members member_of
          JOIN pg_roles member ON member.oid = member_of.member
          JOIN pg_roles granted ON granted.oid = member_of.roleid
         WHERE member.rolname = 'coffre_runtime'
           AND granted.rolname <> 'coffre_app'
    LOOP
        EXECUTE format('REVOKE %I FROM coffre_runtime', membership.rolname);
    END LOOP;
END
$$;
--> statement-breakpoint

GRANT coffre_app TO coffre_runtime WITH ADMIN FALSE, INHERIT TRUE, SET FALSE;
